
 DROP TABLESPACE I1_DATA     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 
 DROP TABLESPACE I1_INDEX     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 
 DROP TABLESPACE M1_DATA     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 
DROP TABLESPACE M1_INDEX     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 
DROP TABLESPACE V1_DATA     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 
 DROP TABLESPACE M1_INDEX     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 
 DROP TABLESPACE M1     INCLUDING CONTENTS         CASCADE CONSTRAINTS; 

drop user M1 cascade ;